# Generated by Django 3.1.2 on 2020-10-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercewebapp', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
